version: "3.8"

services:
  zigbee2mqtt:
    # privileged: true
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt:1.35.1
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=America/Chicago
    devices:
      # Make sure this matched your adapter location
      # - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
      - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231121171832-if00:/dev/ttyACM0
      # - /dev/ttyACM0:/dev/ttyACM0
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # Maps the directory containing Mosquitto configuration files to a location you can edit
      - ./mosquitto:/mosquitto